language: objective-c
osx_image: xcode9.2

env:
  - SCHEME="YoutubeDirectLinkExtractor-macOS"  DESTINATION="arch=x86_64"
  - SCHEME="YoutubeDirectLinkExtractor-iOS"    DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=11.2"

script:
  - xcodebuild clean test -scheme "$SCHEME" -destination "$DESTINATION"
